<form method="POST" action="{{ $action }}" class="form-panel" enctype="multipart/form-data">
    @csrf
    @if($method !== 'POST') @method($method) @endif
    <div class="form-intro"><span class="form-step">01</span><div><h2>Información de la solicitud</h2><p>Los campos marcados con * son obligatorios.</p></div></div>
    @if($errors->any())<x-notice variant="error" title="Revisa la información ingresada."><p>Hay campos que necesitan tu atención.</p></x-notice>@endif
    <div class="form-grid">
        <div class="field span-2"><label for="asunto">Asunto *</label><input id="asunto" name="asunto" type="text" maxlength="150" value="{{ old('asunto', $pqr->asunto ?? '') }}" placeholder="Ej. Solicitud de revisión de factura" required class="@error('asunto') invalid @enderror">@error('asunto')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label for="tipo_pqr_id">Tipo de solicitud *</label><select id="tipo_pqr_id" name="tipo_pqr_id" required class="@error('tipo_pqr_id') invalid @enderror"><option value="">Selecciona una opción</option>@foreach($tipos as $tipo)<option value="{{ $tipo->id }}" @selected(old('tipo_pqr_id', $pqr->tipo_pqr_id ?? '') == $tipo->id)>{{ $tipo->nombre }}</option>@endforeach</select>@error('tipo_pqr_id')<small class="field-error">{{ $message }}</small>@enderror</div>
        @isset($pqr)<div class="field"><label for="estado">Estado de gestión *</label><select id="estado" name="estado" required><option value="radicada" @selected(old('estado', $pqr->estado) === 'radicada')>Radicada</option><option value="en_revision" @selected(old('estado', $pqr->estado) === 'en_revision')>En revisión</option><option value="respondida" @selected(old('estado', $pqr->estado) === 'respondida')>Respondida</option><option value="cerrada" @selected(old('estado', $pqr->estado) === 'cerrada')>Cerrada</option></select></div>@endisset
        @isset($pqr)<div class="field"><label for="prioridad">Prioridad</label><select id="prioridad" name="prioridad"><option value="alta" @selected(old('prioridad', $pqr->prioridad) === 'alta')>Alta</option><option value="media" @selected(old('prioridad', $pqr->prioridad) === 'media')>Media</option><option value="baja" @selected(old('prioridad', $pqr->prioridad) === 'baja')>Baja</option></select></div>@endisset
        @isset($pqr)<div class="field"><label for="assigned_to_id">Responsable</label><select id="assigned_to_id" name="assigned_to_id"><option value="">Sin asignar</option>@foreach($gestores as $gestor)<option value="{{ $gestor->id }}" @selected(old('assigned_to_id', $pqr->assigned_to_id) == $gestor->id)>{{ $gestor->name }}</option>@endforeach</select></div>@endisset
        <div class="field span-2"><label for="descripcion">Descripción *</label><textarea id="descripcion" name="descripcion" rows="6" placeholder="Describe la situación, incluyendo los datos relevantes para atenderla..." required class="@error('descripcion') invalid @enderror">{{ old('descripcion', $pqr->descripcion ?? '') }}</textarea><div class="field-hint"><span>@error('descripcion')<span class="field-error">{{ $message }}</span>@else Incluye fechas, lugares y personas relacionadas. @enderror</span><span id="charCount">0 caracteres</span></div></div>
        <div class="field span-2"><label for="adjuntos">Archivos adjuntos</label><label class="file-drop" for="adjuntos"><span class="file-icon">＋</span><strong>Seleccionar fotos o documentos</strong><small>Hasta 8 archivos de 10 MB cada uno: imágenes, PDF, Word, Excel, texto o ZIP.</small><span class="button subtle">Explorar archivos</span></label><input class="sr-only" id="adjuntos" name="adjuntos[]" type="file" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,.doc,.docx,.xls,.xlsx,.txt,.csv,.zip"><div id="fileList" class="file-list" aria-live="polite"></div>@error('adjuntos.*')<small class="field-error">{{ $message }}</small>@enderror</div>
        @isset($pqr)<div class="field span-2 pqr-readonly-dates" role="group" aria-labelledby="pqr-readonly-dates-title"><strong id="pqr-readonly-dates-title">Fechas de la radicación</strong><dl><div><dt>Fecha de radicación</dt><dd>{{ str_replace('.', '', $pqr->fecha_radicacion->locale('es')->translatedFormat('d M Y')) }}</dd></div><div><dt>Fecha límite de respuesta</dt><dd>{{ $pqr->fecha_limite_respuesta ? str_replace('.', '', $pqr->fecha_limite_respuesta->locale('es')->translatedFormat('d M Y')) : 'Sin fecha registrada' }}</dd></div></dl><p>El plazo fue calculado automáticamente en días hábiles y no puede modificarse desde la gestión administrativa.</p></div>@endisset
    </div>
    <div class="form-actions">
        @isset($pqr)<button type="submit" form="delete-form" class="button danger">Eliminar</button>@endisset
        <div><a href="{{ route('pqrs.index') }}" class="button ghost">Cancelar</a><button type="submit" class="button primary">{{ $submitLabel }} <span>→</span></button></div>
    </div>
</form>
@isset($pqr)@error('pqr')<div class="notice error" role="alert"><span>!</span><div><strong>{{ $message }}</strong></div></div>@enderror<form id="delete-form" action="{{ route('pqrs.destroy', $pqr) }}" method="POST" hidden data-confirm="Eliminar solicitud" data-confirm-message="Esta acción eliminará la solicitud y sus archivos. No se puede deshacer.">@csrf @method('DELETE')</form>@endisset
