@extends('layouts.app')
@section('titulo', 'Documento')
@section('titulo_pagina', 'Documento')
@section('contenido')
@php
    $tipo = ['documento_general' => 'Documento general', 'reglamento' => 'Reglamento', 'manual_convivencia' => 'Manual de convivencia', 'acta' => 'Acta'];
    $categoria = ['normativo' => 'Normativo', 'administrativo' => 'Administrativo', 'gobierno_copropiedad' => 'Gobierno de la Copropiedad', 'contractual' => 'Contractual', 'financiero' => 'Financiero', 'comunicaciones' => 'Comunicaciones', 'otro' => 'Otro'];
    $acceso = ['administrativo' => 'Administrativo', 'interno' => 'Interno', 'comunidad' => 'Comunidad'];
    $estadoVersion = ['borrador' => 'Borrador', 'pendiente_aprobacion' => 'Pendiente de aprobación', 'aprobada' => 'Aprobada', 'rechazada' => 'Rechazada'];
    $versiones = $documento->versiones->sortByDesc('numero');
    $vigente = $documento->versionVigente();
@endphp
    @if($errors->any())<x-notice variant="error" title="No fue posible completar la acción documental."><p>Revisa los datos y vuelve a intentarlo.</p></x-notice>@endif
    <section class="page-heading compact detail-heading"><div><a class="back-link" href="{{ route('documentos.index') }}">← Volver a Documentos</a><span class="eyebrow">{{ $tipo[$documento->tipo->value] ?? $documento->tipo->value }}</span><h1>{{ $documento->titulo }}</h1><p>{{ $documento->descripcion ?: 'Sin descripción registrada.' }}</p></div>@can('archive',$documento)<form method="POST" action="{{ route('documentos.archive',$documento) }}" data-confirm="Archivar Documento" data-confirm-message="El Documento dejará de estar activo para la Copropiedad.">@csrf @method('PATCH')<button class="button subtle">Archivar Documento</button></form>@endcan</section>
    <div class="detail-grid document-detail-grid"><aside class="detail-card metadata-card pqrs-summary-card"><span class="eyebrow">Documento</span><h2>{{ $documento->estado->value === 'activo' ? 'Activo' : 'Archivado' }}</h2><div class="next-step"><span class="eyebrow">Versión vigente</span><p>@if($vigente)Versión {{ $vigente->numero }} disponible desde {{ $vigente->vigente_desde?->translatedFormat('d M Y') ?? 'la fecha registrada' }}.@else No hay una versión aprobada y vigente disponible.@endif</p></div><dl><div><dt>Categoría</dt><dd>{{ $categoria[$documento->categoria->value] ?? $documento->categoria->value }}</dd></div><div><dt>Nivel de acceso</dt><dd>{{ $acceso[$documento->nivel_acceso->value] ?? $documento->nivel_acceso->value }}</dd></div><div><dt>Propietario documental</dt><dd>{{ $documento->propietarioDocumental?->name ?? 'Sin propietario' }}</dd></div><div><dt>Versiones</dt><dd>{{ $versiones->count() }}</dd></div></dl></aside>
        <article class="detail-card main-detail"><div class="detail-section"><div class="attachments-heading"><div><span class="eyebrow">Versiones</span><h2>Versión vigente y otras versiones</h2></div><span>{{ $versiones->count() }} registrada(s)</span></div>@forelse($versiones as $version)@php($esVigente = $vigente?->is($version))<article class="document-version-card {{ $esVigente ? 'current' : '' }}"><div class="document-version-heading"><div><span class="status {{ $version->estado->value }}"><i></i>{{ $estadoVersion[$version->estado->value] ?? $version->estado->value }}</span><strong>Versión {{ $version->numero }}</strong><small>{{ $version->nombre_original }}</small></div>@if($esVigente)<span class="current-version-badge">Vigente</span>@endif</div><p>Vigencia: {{ $version->vigente_desde?->translatedFormat('d M Y') ?? 'Sin fecha de inicio' }} — {{ $version->vigente_hasta?->translatedFormat('d M Y') ?? 'Sin fecha de finalización' }}@if($version->sustituyeVersion) · Sustituye la versión {{ $version->sustituyeVersion->numero }}@endif</p><div class="document-version-actions">@if($esVigente)@can('view', $documento)<a class="button subtle" href="{{ route('documentos.versions.download', [$documento, $version]) }}">↓ Descargar</a>@endcan @endif @if($version->estado->value === 'borrador')@can('update', $documento)<form method="POST" action="{{ route('documentos.versions.submit',[$documento,$version]) }}" data-confirm="Someter versión" data-confirm-message="La versión quedará pendiente de aprobación.">@csrf<button class="button subtle">Someter a aprobación</button></form>@endcan @endif @if($version->estado->value === 'pendiente_aprobacion')@can('approve', $documento)<details class="document-action"><summary class="button primary">Aprobar versión</summary><form method="POST" action="{{ route('documentos.versions.approve',[$documento,$version]) }}" data-confirm="Aprobar versión" data-confirm-message="Confirma la vigencia de esta versión.">@csrf<div class="field"><label>Vigente desde<input name="vigente_desde" type="date" required></label></div><div class="field"><label>Vigente hasta (opcional)<input name="vigente_hasta" type="date"></label></div><button class="button primary">Confirmar aprobación</button></form></details><details class="document-action"><summary class="button danger">Rechazar versión</summary><form method="POST" action="{{ route('documentos.versions.reject',[$documento,$version]) }}" data-confirm="Rechazar versión" data-confirm-message="La observación quedará registrada en el historial.">@csrf<div class="field"><label>Observación requerida<textarea name="observacion_rechazo" required></textarea></label></div><button class="button danger">Confirmar rechazo</button></form></details>@endcan @endif</div></article>@empty<div class="empty-state"><span class="empty-illustration"><i></i><b>✓</b></span><h3>Sin versiones registradas</h3><p>Este Documento aún no tiene versiones cargadas.</p></div>@endforelse</div>
            @can('update',$documento)<div class="detail-section"><span class="eyebrow">Acción disponible</span><h2>Cargar nueva versión</h2><p class="section-help">La nueva versión quedará en borrador hasta que sea sometida y aprobada.</p><form method="POST" action="{{ route('documentos.versions.store',$documento) }}" enctype="multipart/form-data" class="document-upload-form">@csrf<div class="field"><label>Archivo<input type="file" name="archivo" required></label>@error('archivo')<small class="field-error">{{ $message }}</small>@enderror</div><div class="field"><label>Versión sustituida (opcional)<select name="sustituye_version_id"><option value="">No sustituye una versión</option>@foreach($versiones as $version)<option value="{{ $version->id }}">Versión {{ $version->numero }} · {{ $estadoVersion[$version->estado->value] ?? $version->estado->value }}</option>@endforeach</select></label><small class="field-help">Solo se muestran versiones de este Documento.</small></div><button class="button primary">Cargar versión</button></form></div>@endcan
            <div class="detail-section"><span class="eyebrow">Historial</span><h2>Secuencia de actuaciones</h2><div class="activity-timeline">@forelse($documento->actuaciones as $actuacion)<div class="activity-item"><i></i><div><strong>{{ $actuacion->detalle }}</strong><span>{{ $actuacion->nombre_actor ?? 'Sistema' }}</span></div></div>@empty<div class="empty-attachments"><p>Aún no hay actuaciones registradas para este Documento.</p></div>@endforelse</div></div></article></div>
@endsection
