@extends('layouts.app')
@section('titulo', 'PQRS')
@section('titulo_pagina', 'Expediente PQRS')
@section('contenido')
    @php
        $diasRestantes = $pqr->remaining_days;
        $plazo = match (true) {
            $diasRestantes === null => ['Sin fecha límite', 'No se definió una fecha límite para esta PQRS.', 'neutral'],
            $pqr->is_overdue => [abs($diasRestantes) === 1 ? 'Venció hace 1 día hábil' : 'Venció hace '.abs($diasRestantes).' días hábiles', 'Plazo vencido', 'overdue'],
            $pqr->estado === 'respondida' || $pqr->estado === 'cerrada' => ['Fecha límite: '.str_replace('.', '', $pqr->fecha_limite_respuesta->locale('es')->translatedFormat('d M Y')), 'La gestión ya no está pendiente de respuesta.', 'neutral'],
            $diasRestantes === 0 => ['Vence hoy', 'Atiende esta PQRS dentro de la jornada.', 'due-today'],
            $diasRestantes === 1 => ['Vence en 1 día hábil', 'Fecha límite: '.str_replace('.', '', $pqr->fecha_limite_respuesta->locale('es')->translatedFormat('d M Y')), 'upcoming'],
            default => ['Vence en '.$diasRestantes.' días hábiles', 'Fecha límite: '.str_replace('.', '', $pqr->fecha_limite_respuesta->locale('es')->translatedFormat('d M Y')), 'upcoming'],
        };
        $respuestasVisibles = $pqr->replies;
        $respuestasEnviadas = $pqr->replies->where('is_draft', false)->count();
    @endphp

    <section class="expediente-heading" aria-labelledby="expediente-title">
        <div class="expediente-heading-copy"><a class="back-link" href="{{ route('pqrs.index') }}">← Volver a PQRS</a><p class="eyebrow">Expediente · PQR-{{ str_pad($pqr->id, 4, '0', STR_PAD_LEFT) }}</p><h1 id="expediente-title">{{ $pqr->asunto }}</h1><p class="expediente-heading-meta">Radicada por {{ $pqr->user?->name ?? 'Usuario no disponible' }} · {{ str_replace('.', '', $pqr->fecha_radicacion->locale('es')->translatedFormat('d M Y')) }}</p></div>
        <div class="expediente-heading-actions">@if($puedeGestionar)<span class="priority-badge prioridad-{{ $pqr->prioridad }}" aria-label="Prioridad {{ $pqr->prioridad_label }}">{{ $pqr->prioridad_label }}</span>@endif<span class="status {{ $pqr->estado }}"><i></i>{{ $pqr->estado_label }}</span></div>
    </section>

    <div class="expediente-layout">
        <aside class="expediente-summary" aria-label="Resumen de la PQRS">
            <section class="expediente-summary-section"><p class="eyebrow">Situación actual</p><h2>{{ $pqr->estado_label }}</h2><div class="expediente-deadline {{ $plazo[2] }}"><strong>{{ $plazo[0] }}</strong><span>{{ $plazo[1] }}</span></div></section>
            <section class="expediente-summary-section"><p class="eyebrow">Responsabilidad</p><dl class="expediente-facts"><div><dt>Responsable</dt><dd>{{ $pqr->assignee?->name ?? 'Sin asignar' }}</dd></div><div><dt>Radicador</dt><dd>{{ $pqr->user?->name ?? 'No disponible' }}</dd></div><div><dt>Tipo</dt><dd>{{ $pqr->tipoPqr?->nombre ?? 'Sin tipo' }}</dd></div>@if($puedeGestionar)<div><dt>Prioridad</dt><dd><span class="priority-badge prioridad-{{ $pqr->prioridad }}">{{ $pqr->prioridad_label }}</span></dd></div>@endif<div><dt>Fecha de radicación</dt><dd>{{ str_replace('.', '', $pqr->fecha_radicacion->locale('es')->translatedFormat('d M Y')) }}</dd></div></dl></section>
            @if($puedeGestionar)<section class="expediente-summary-section administrative-management" aria-labelledby="gestion-administrativa-title"><p class="eyebrow">Solo equipo autorizado</p><h2 id="gestion-administrativa-title">Gestión administrativa</h2><p>Actualiza el estado y el responsable de esta PQRS.</p><p>Los cambios quedan registrados en el historial.</p><a href="{{ route('pqrs.edit', $pqr) }}" class="button primary">Gestionar PQRS <span aria-hidden="true">→</span></a></section>@endif
            <section class="expediente-summary-section"><p class="eyebrow">Próximo paso</p><p class="expediente-next-step">{{ $proximoPaso }}</p></section>
            @if($puedeGestionar)
                @php
                    $etiquetasOriginales = $pqr->tags->pluck('id')->map(fn ($id) => (string) $id)->values();
                    $etiquetasSeleccionadas = collect(old('tags', $etiquetasOriginales->all()))->map(fn ($id) => (string) $id);
                    $hayErroresEtiquetas = $errors->has('tags') || $errors->get('tags.*') !== [];
                    $cantidadSeleccionada = $etiquetasSeleccionadas->intersect($availableTags->pluck('id')->map(fn ($id) => (string) $id))->count();
                @endphp
                <section class="expediente-summary-section expediente-tags" aria-labelledby="etiquetas-title">
                    <p class="eyebrow">Organización del expediente</p><h2 id="etiquetas-title">Etiquetas</h2>
                    @if($availableTags->isEmpty())
                        <div class="tag-empty-state"><strong>No hay etiquetas disponibles</strong><p>Cuando exista un catálogo autorizado, podrás asignar etiquetas desde este expediente.</p></div>
                    @else
                        <form method="POST" action="{{ route('pqrs.tags.sync', $pqr) }}" class="tag-assignment-form" data-tag-assignment>
                            @csrf @method('PATCH')
                            <p class="tag-help">Guardar reemplaza la selección actual. Desmarcar una etiqueta la retira de esta PQRS.</p>
                            @if($hayErroresEtiquetas)
                                <div class="tag-error-summary" id="tag-errors" role="alert" tabindex="-1" data-tag-error><strong>No fue posible guardar las etiquetas.</strong><ul>@foreach($errors->get('tags') as $error)<li>{{ $error }}</li>@endforeach @foreach($errors->get('tags.*') as $messages)@foreach($messages as $error)<li>{{ $error }}</li>@endforeach @endforeach</ul></div>
                            @endif
                            <fieldset class="tag-fieldset" aria-describedby="tag-help{{ $hayErroresEtiquetas ? ' tag-errors' : '' }}">
                                <legend>Selecciona las etiquetas de esta PQRS</legend><span id="tag-help" class="sr-only">Guardar reemplaza la selección actual y desmarcar retira una etiqueta.</span>
                                <div class="tag-options">@foreach($availableTags as $tag)<label style="--tag:{{ $tag->color }}" class="{{ $tag->activo ? '' : 'is-inactive' }}"><input type="checkbox" name="tags[]" value="{{ $tag->id }}" @checked($etiquetasSeleccionadas->contains((string) $tag->id)) data-originally-checked="{{ $etiquetasOriginales->contains((string) $tag->id) ? 'true' : 'false' }}"><span class="tag-color" aria-hidden="true"></span><span>{{ $tag->name }} @unless($tag->activo)<small>Desactivada</small>@endunless</span></label>@endforeach</div>
                            </fieldset>
                            <p class="tag-selection-summary" data-tag-summary role="status" aria-live="polite">{{ $cantidadSeleccionada }} {{ $cantidadSeleccionada === 1 ? 'etiqueta seleccionada' : 'etiquetas seleccionadas' }}.</p>
                            <p class="tag-original-state">Selección guardada: {{ $etiquetasOriginales->count() ? $etiquetasOriginales->count().' '.($etiquetasOriginales->count() === 1 ? 'etiqueta' : 'etiquetas') : 'ninguna etiqueta' }}.</p>
                            <div class="tag-form-actions"><button class="button subtle" type="button" data-tag-restore disabled>Restaurar selección</button><button class="button primary" type="submit" data-tag-submit>Guardar etiquetas</button></div>
                        </form>
                    @endif
                </section>
            @endif
            @if(! $puedeGestionar)<div class="locked-note"><span aria-hidden="true">⌾</span><p><strong>Seguimiento disponible</strong>Verás los avances autorizados de esta PQRS.</p></div>@endif
        </aside>

        <main class="expediente-content" aria-label="Contenido del expediente">
            <section class="expediente-section" aria-labelledby="descripcion-title"><p class="eyebrow">Información principal</p><h2 id="descripcion-title">Descripción de la PQRS</h2><p class="description-text">{{ $pqr->descripcion }}</p></section>

            <section class="expediente-section" aria-labelledby="respuestas-oficiales-title"><div class="expediente-section-heading"><div><p class="eyebrow">Comunicación con el radicador</p><h2 id="respuestas-oficiales-title">Respuestas oficiales</h2></div><span>{{ $respuestasEnviadas }} {{ $respuestasEnviadas === 1 ? 'enviada' : 'enviadas' }}</span></div>@php($oficiales = $respuestasVisibles->where('is_draft', false))@forelse($oficiales as $reply)<article class="reply-card official" aria-label="Respuesta oficial enviada"><div class="reply-heading"><span class="avatar small" aria-hidden="true">{{ Str::upper(Str::substr($reply->user?->name ?? 'NA', 0, 2)) }}</span><div><strong>{{ $reply->user?->name ?? 'Usuario' }}</strong><small>{{ $reply->sent_at?->locale('es')->diffForHumans() }}</small></div><span class="official-badge" aria-label="Respuesta oficial, inmutable">Respuesta oficial</span></div><p>{{ $reply->body }}</p>@if($reply->attachments)<div class="reply-files" role="list" aria-label="Archivos adjuntos de la respuesta oficial">@foreach($reply->attachments as $index => $file)<a href="{{ route('pqrs.replies.download', [$pqr, $reply, $index]) }}" role="listitem">Descargar {{ $file['name'] }}</a>@endforeach</div>@endif</article>@empty<div class="expediente-empty" role="status"><p>Aún no se han enviado respuestas oficiales al radicador.</p></div>@endforelse</section>

            @php($borradoresPropios = $respuestasVisibles->where('is_draft', true)->where('user_id', auth()->id()))@if($puedeGestionar && $borradoresPropios->isNotEmpty())<section class="expediente-section" aria-labelledby="borradores-title"><div class="expediente-section-heading"><div><p class="eyebrow">Solo equipo autorizado</p><h2 id="borradores-title">Borradores propios</h2></div><span>{{ $borradoresPropios->count() }} {{ $borradoresPropios->count() === 1 ? 'borrador' : 'borradores' }}</span></div><p class="section-help">Estos borradores son internos y no han sido enviados al radicador.</p>@foreach($borradoresPropios as $reply)<article class="reply-card draft" aria-label="Borrador propio, no enviado"><div class="reply-heading"><span class="avatar small" aria-hidden="true">{{ Str::upper(Str::substr($reply->user?->name ?? 'NA', 0, 2)) }}</span><div><strong>{{ $reply->user?->name ?? 'Usuario' }}</strong><small>Borrador interno · No enviado</small></div><span class="draft-badge" aria-label="Borrador interno, no enviado al radicador">Borrador interno</span></div><p>{{ $reply->body }}</p>@if($reply->attachments)<div class="reply-files" role="list" aria-label="Archivos adjuntos del borrador">@foreach($reply->attachments as $index => $file)<a href="{{ route('pqrs.replies.download', [$pqr, $reply, $index]) }}" role="listitem">Descargar {{ $file['name'] }}</a>@endforeach</div>@endif<form method="POST" action="{{ route('pqrs.replies.update', [$pqr, $reply]) }}" enctype="multipart/form-data">@csrf @method('PUT')<input type="hidden" name="idempotency_key" value="{{ $replyOperationKeys['drafts'][$reply->id]['update_draft'] }}"><div class="field"><label for="draft-body-{{ $reply->id }}">Editar borrador</label><textarea id="draft-body-{{ $reply->id }}" name="body" rows="5" required>{{ $reply->body }}</textarea><input name="attachments[]" type="file" multiple></div><button class="button subtle">Actualizar borrador</button></form><div class="reply-actions"><form method="POST" action="{{ route('pqrs.replies.send', [$pqr, $reply]) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ $replyOperationKeys['drafts'][$reply->id]['send_draft'] }}"><button class="button primary" data-confirm="Enviar borrador" data-confirm-message="El borrador se enviará como respuesta oficial al radicador.">Enviar borrador</button></form><form method="POST" action="{{ route('pqrs.replies.destroy', [$pqr, $reply]) }}">@csrf @method('DELETE')<input type="hidden" name="idempotency_key" value="{{ $replyOperationKeys['drafts'][$reply->id]['delete_draft'] }}"><button class="button subtle">Eliminar borrador</button></form></div></article>@endforeach</section>@endif

            @if($puedeGestionar)<section class="expediente-section reply-editor" aria-labelledby="respuesta-form-title"><p class="eyebrow">Acción disponible</p><h2 id="respuesta-form-title">Enviar respuesta al radicador</h2>@if($errors->has('body') || $errors->has('attachments') || $errors->has('attachments.*'))<div class="reply-error-summary" id="reply-errors" role="alert" tabindex="-1" data-first-error><strong>No fue posible procesar la respuesta.</strong><ul>@foreach($errors->get('body') as $error)<li>{{ $error }}</li>@endforeach @foreach($errors->get('attachments') as $error)<li>{{ $error }}</li>@endforeach @foreach($errors->get('attachments.*') as $messages)@foreach($messages as $error)<li>{{ $error }}</li>@endforeach @endforeach</ul></div>@endif<form method="POST" action="{{ route('pqrs.replies.store', $pqr) }}" enctype="multipart/form-data" data-reply-form>@csrf<input type="hidden" name="create_draft_key" value="{{ $replyOperationKeys['create_draft'] }}"><input type="hidden" name="send_reply_key" value="{{ $replyOperationKeys['send_reply'] }}">@if($templates->isNotEmpty())<div class="field"><label for="responseTemplate">Usar plantilla</label><select id="responseTemplate"><option value="">Seleccionar plantilla</option>@foreach($templates as $template)<option data-body="{{ $template->body }}">{{ $template->name }}</option>@endforeach</select></div>@endif <div class="field"><label for="body">Mensaje</label><textarea id="body" name="body" rows="7" required placeholder="Escribe una respuesta clara y completa..." aria-describedby="body-hint{{ $errors->has('body') ? ' body-error' : '' }}" @error('body') aria-invalid="true" @enderror>{{ old('body') }}</textarea><span id="body-hint" class="field-hint">La respuesta será visible para el radicador al enviarla.</span>@error('body')<small id="body-error" class="field-error" role="alert">{{ $message }}</small>@enderror</div><div class="field"><label for="replyAttachments">Adjuntar documentos</label><input id="replyAttachments" name="attachments[]" type="file" multiple aria-describedby="attachments-hint" @error('attachments') aria-invalid="true" @enderror @error('attachments.*') aria-invalid="true" @enderror><span id="attachments-hint" class="field-hint">Máximo 5 archivos, 10 MB cada uno. Formatos: JPG, PNG, WebP, PDF, DOC, DOCX, XLS, XLSX, TXT, CSV, ZIP.</span>@error('attachments')<small class="field-error" role="alert">{{ $message }}</small>@enderror @error('attachments.*')<small class="field-error" role="alert">{{ $message }}</small>@enderror</div><div class="reply-actions"><button class="button subtle" name="action" value="draft" data-submit-label="Guardando…">Guardar borrador interno</button><button class="button primary" name="action" value="send" data-confirm="Enviar respuesta" data-confirm-message="La respuesta será visible para el radicador y la PQRS cambiará a Respondida." data-submit-label="Enviando…">Enviar respuesta <span aria-hidden="true">→</span></button></div></form></section>@endif

            <section class="expediente-section" aria-labelledby="adjuntos-title"><div class="expediente-section-heading"><div><p class="eyebrow">Soportes</p><h2 id="adjuntos-title">Archivos adjuntos</h2></div><span>{{ $pqr->attachments->count() }} {{ $pqr->attachments->count() === 1 ? 'archivo' : 'archivos' }}</span></div>@forelse($pqr->attachments as $attachment)<a class="attachment-row" href="{{ route('attachments.download', $attachment) }}"><span class="attachment-icon">{{ str_starts_with($attachment->mime_type, 'image/') ? 'IMG' : 'DOC' }}</span><span><strong>{{ $attachment->original_name }}</strong><small>{{ number_format($attachment->size / 1024, 0) }} KB</small></span><span class="download-icon" aria-hidden="true">↓</span></a>@empty<div class="expediente-empty"><p>Esta PQRS no tiene archivos adjuntos.</p></div>@endforelse</section>

            @if($puedeGestionar)<section class="expediente-section internal-comments" aria-labelledby="comentarios-title"><p class="eyebrow">Solo equipo autorizado</p><h2 id="comentarios-title">Comentarios internos</h2><p class="section-help">Notas administrativas del equipo. No son visibles para el radicador ni se incluyen en las respuestas oficiales.</p><form method="POST" action="{{ route('pqrs.comments.store',$pqr) }}">@csrf<div class="field"><label class="sr-only" for="internalComment">Agregar comentario interno</label><textarea id="internalComment" name="body" rows="3" required placeholder="Agrega una nota para el equipo..."></textarea></div><button class="button subtle" data-submit-label="Guardando…">Agregar comentario interno</button></form><div class="comment-list" role="list" aria-label="Comentarios internos del equipo">@forelse($pqr->internalComments as $comment)<article role="listitem"><span class="avatar small" aria-hidden="true">{{ Str::upper(Str::substr($comment->user?->name ?? 'NA',0,2)) }}</span><div><strong>{{ $comment->user?->name ?? 'Usuario' }}</strong><p>{{ $comment->body }}</p><small>{{ $comment->created_at->locale('es')->diffForHumans() }}</small></div></article>@empty<p class="empty-comment">No hay comentarios internos.</p>@endforelse</div></section>@endif

            <section class="expediente-section" aria-labelledby="historial-title"><p class="eyebrow">Trazabilidad</p><h2 id="historial-title">Historial de actuaciones</h2><div class="activity-timeline">@forelse($pqr->activities as $activity)<div class="activity-item"><i aria-hidden="true"></i><div><strong>{{ $activity->description }}</strong><span>{{ $activity->user?->name ?? 'Sistema' }} · {{ $activity->created_at->locale('es')->diffForHumans() }}</span></div></div>@empty<div class="expediente-empty"><p>Aún no hay actividad registrada para esta PQRS.</p></div>@endforelse</div></section>
            @if($pqr->user_id === auth()->id() && in_array($pqr->estado, ['respondida','cerrada']))<section class="expediente-section satisfaction-card" aria-labelledby="satisfaccion-title"><h2 id="satisfaccion-title">¿Cómo fue la atención?</h2>@if($pqr->satisfactionSurvey)<strong>{{ str_repeat('★',$pqr->satisfactionSurvey->rating) }}{{ str_repeat('☆',5-$pqr->satisfactionSurvey->rating) }}</strong><p>Gracias por compartir tu opinión.</p>@else<form method="POST" action="{{ route('pqrs.survey.store',$pqr) }}">@csrf<div class="rating-input">@foreach(range(5,1) as $rating)<input id="rating{{ $rating }}" type="radio" name="rating" value="{{ $rating }}" required><label for="rating{{ $rating }}">★</label>@endforeach</div><textarea name="comment" rows="2" placeholder="Comentario opcional"></textarea><button class="button primary">Enviar valoración</button></form>@endif</section>@endif
        </main>
    </div>
@endsection
